In [1]:
import pandas as pd


In [2]:
df = pd.read_csv("../data/Combined_Cycle_Power_Plant.csv")

In [3]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
X = df.iloc[:, 0:4].values
X.shape

(47840, 4)

In [8]:
y = df.PE.values

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                    test_size = 0.3, random_state = 1)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler() 

In [12]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
scaler.mean_

array([   19.63243669,    54.24510481,  1013.25845288,    73.238039  ])

In [14]:
scaler.var_

array([  55.62567202,  161.25090158,   35.58858135,  214.25008888])

In [15]:
X_train_std = scaler.transform(X_train)

In [21]:
pd.DataFrame(X).sample(10)

0      1        2      3
5318   34.40  77.95  1009.83  57.86
8665   19.44  59.21  1018.50  88.35
3448   19.76  58.79  1017.37  89.09
36221  25.97  43.21  1011.90  88.73
18148  25.21  49.82  1016.44  63.14
28743  20.08  62.52  1017.99  75.74
21708  11.76  40.96  1023.22  81.31
34955  12.67  41.16  1016.92  92.80
8732   21.63  71.85  1009.44  76.89
34365  25.04  51.95  1005.56  66.53

In [30]:
pd.DataFrame(X_train_std).head(3)

0         1         2         3
0  0.068054 -0.576062  0.234938 -0.616101
1 -0.740446 -0.721749  1.678208  0.681954
2  0.703591 -0.148451  0.199736 -0.331212

In [31]:
X_test_std = scaler.transform(X_test)
pd.DataFrame(X_test_std).head(3)

0         1         2         3
0 -0.389157 -0.728049  1.706705 -0.857949
1  0.847056  0.894982  0.184649 -1.414063
2  1.812428  1.272193 -1.598905 -1.315684

In [22]:
import math

In [28]:
math.sqrt(1000000 ** 2 + 10 ** 2) - math.sqrt(1000000 ** 2 + 11 ** 2)

-1.0499963536858559e-05

In [29]:
math.sqrt(1000001 ** 2 + 10 ** 2) - math.sqrt(1000000 ** 2 + 10 ** 2)

0.9999999998835847

In [32]:
from sklearn.linear_model import LinearRegression

In [42]:
lr = LinearRegression()

In [44]:
lr.fit(X_train_std, y_train) 
# this step machine is learning the parameter values

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [45]:
lr.coef_

array([-14.73349561,  -2.96511136,   0.38338609,  -2.30766511])

In [41]:
lr.predict(X_test_std)

array([ 464.96157532,  442.63515875,  426.38256103, ...,  432.9305107 ,
        479.08900269,  457.59314259])

In [47]:
df = pd.read_csv("https://raw.githubusercontent.com/abulbasar/data/master/startups.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          48 non-null float64
Administration     50 non-null float64
Marketing Spend    47 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [48]:
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11              NaN    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47        NaN       135426.92              NaN  California   42559.73
48     542.05        51743.15              NaN    New York   35673.41
49        NaN       116983.80         45173.06  California   14681.40

In [61]:
na_idx = df[df.isnull().sum(axis = 1) > 0].index
df.iloc[na_idx]

R&D Spend  Administration  Marketing Spend       State     Profit
19   86419.70       153514.11              NaN    New York  122776.86
47        NaN       135426.92              NaN  California   42559.73
48     542.05        51743.15              NaN    New York   35673.41
49        NaN       116983.80         45173.06  California   14681.40

In [59]:
df.fillna(df.median()).iloc[na_idx]

R&D Spend  Administration  Marketing Spend       State     Profit
19  86419.700       153514.11        229160.95    New York  122776.86
47  74661.715       135426.92        229160.95  California   42559.73
48    542.050        51743.15        229160.95    New York   35673.41
49  74661.715       116983.80         45173.06  California   14681.40

In [60]:
df.median()

R&D Spend           74661.715
Administration     122699.795
Marketing Spend    229160.950
Profit             107978.190
dtype: float64

In [62]:
df.head(3)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39

In [63]:
df = df.fillna(df.mean())

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [67]:
df_dummy = pd.get_dummies(df, drop_first=True)
df_dummy.head(3)

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83              0   
1  162597.70       151377.59        443898.53  191792.06              0   
2  153441.51       101145.55        407934.54  191050.39              1   

   State_New York  
0               1  
1               0  
2               0

In [73]:
X = df_dummy.iloc[:, [0, 1, 2, 4, 5]].values
y = df_dummy.Profit

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                    test_size = 0.3, random_state = 1)

0          1              2    3    4
0    23640.930000   96189.63  148001.110000  0.0  0.0
1    76793.349583  116983.80   45173.060000  0.0  0.0
2    75328.870000  144135.98  134050.070000  1.0  0.0
3    73994.560000  122782.75  303319.260000  1.0  0.0
4    91992.390000  135495.07  252664.930000  0.0  0.0
5    27892.920000   84710.77  164470.710000  1.0  0.0
6    94657.160000  145077.58  282574.310000  0.0  1.0
7     1000.230000  124153.04    1903.930000  0.0  1.0
8    77044.010000   99281.34  140574.810000  0.0  1.0
9    67532.530000  105751.03  304768.730000  1.0  0.0
10  142107.340000   91391.77  366168.420000  1.0  0.0
11   55493.950000  103057.49  214634.810000  1.0  0.0
12  119943.240000  156547.42  256512.920000  1.0  0.0
13   61994.480000  115641.28   91131.240000  1.0  0.0
14  101913.080000  110594.11  229160.950000  1.0  0.0
15   66051.520000  182645.56  118148.200000  1.0  0.0
16   22177.740000  154806.14   28334.720000  0.0  0.0
17   46426.070000  157693.92  210797.670000  0.0  0.0
18   91749.160000  114175.79  294919.570000  1.0  0.0
19   76253.860000  113867.30  298664.470000  0.0  0.0
20   64664.710000  139553.16  137962.620000  0.0  0.0
21  134615.460000  147198.87  127716.820000  0.0  0.0
22  130298.130000  145530.06  323876.680000  1.0  0.0
23   76793.349583  135426.92  224494.784894  0.0  0.0
24  162597.700000  151377.59  443898.530000  0.0  0.0
25   78013.110000  121597.55  264346.060000  0.0  0.0
26  165349.200000  136897.80  471784.100000  0.0  1.0
27  114523.610000  122616.84  261776.230000  0.0  1.0
28  131876.900000   99814.71  362861.360000  0.0  1.0
29  100671.960000   91790.61  249744.550000  0.0  0.0
30  123334.880000  108679.17  304981.620000  0.0  0.0
31  120542.520000  148718.95  311613.290000  0.0  1.0
32   93863.750000  127320.38  249839.440000  1.0  0.0
33   15505.730000  127382.30   35534.170000  0.0  1.0
34   44069.950000   51283.14  197029.420000  0.0  0.0

In [76]:
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_train)

In [78]:
import numpy as np

In [79]:
X = np.array([
    [3, 5, 1],
    [5, 9, 10],
    [1, 2, 3],
    [-3, 2, 10]
])
X

array([[ 3,  5,  1],
       [ 5,  9, 10],
       [ 1,  2,  3],
       [-3,  2, 10]])

In [80]:
from sklearn.preprocessing import PolynomialFeatures

In [90]:
poly = PolynomialFeatures(degree=2, include_bias=False)

In [91]:
pd.DataFrame(poly.fit_transform(X))

0    1     2     3     4     5     6     7      8
0  3.0  5.0   1.0   9.0  15.0   3.0  25.0   5.0    1.0
1  5.0  9.0  10.0  25.0  45.0  50.0  81.0  90.0  100.0
2  1.0  2.0   3.0   1.0   2.0   3.0   4.0   6.0    9.0
3 -3.0  2.0  10.0   9.0  -6.0 -30.0   4.0  20.0  100.0

In [87]:
X[:, 1] ** 2 

array([25, 81,  4,  4])

# Load Power Plan dataset, for the following
	1.	Load the dataset
	2.	Generate X and y where X is feature matrix, y is output vector (PE)
	3.	Split X, y into training and test set with split ratio 70/30 with random seed = 100
	4.	Build a linear regression model on training data and calculate rmse for both training and testing dataset
	5.	Create a polynomial transformation on X with degree 2
	6.	 Repeat step 4 for new polynomial features. 


In [93]:
df = pd.read_csv("../data/Combined_Cycle_Power_Plant.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47840 entries, 0 to 47839
Data columns (total 5 columns):
AT    47840 non-null float64
V     47840 non-null float64
AP    47840 non-null float64
RH    47840 non-null float64
PE    47840 non-null float64
dtypes: float64(5)
memory usage: 1.8 MB


In [96]:
X = df.iloc[:, 0:4].values
y = df.PE.values

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                            test_size = 0.3, random_state = 100)

In [108]:
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.fit_transform(X_test)

In [109]:
lr = LinearRegression()

In [110]:
lr.fit(X_train_std, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [111]:
y_test_pred = lr.predict(X_test_std)

In [105]:
from sklearn.metrics import mean_squared_error

In [106]:
def rmse(y_true, y_test): 
    return np.sqrt(mean_squared_error(y_true, y_test))

In [112]:
rmse(y_test, y_test_pred)

4.5785372352343563

In [114]:
rmse(y_train, lr.predict(X_train_std))

4.5501157106963399

In [115]:
poly = PolynomialFeatures(degree=2)

In [119]:
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
X_train_poly_std = scaler.fit_transform(X_train_poly)
X_test_poly_std = scaler.transform(X_test_poly)

In [120]:
lr.fit(X_train_poly_std, y_train)
rmse(y_train, lr.predict(X_train_poly_std))

4.2462838904304334

In [121]:
rmse(y_test, lr.predict(X_test_poly_std))

4.2769882980220748

In [122]:
poly = PolynomialFeatures(degree=5)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
X_train_poly_std = scaler.fit_transform(X_train_poly)
X_test_poly_std = scaler.transform(X_test_poly)
lr.fit(X_train_poly_std, y_train)
rmse(y_train, lr.predict(X_train_poly_std)), rmse(y_test, lr.predict(X_test_poly_std))

(3.9614223883709823, 3.9892284276685395)

In [123]:
from sklearn.pipeline import Pipeline

In [128]:
class MyTransformation:
    
    def __init__(self):
        pass
    
    def fit(self, X, y):
        pass
    
    def predict(self, X, y):
        pass
    

In [124]:
pipeline = Pipeline([
    ("poly", PolynomialFeatures(degree=2)),
    ("scaler", StandardScaler()),
    ("lr", LinearRegression()),
    ("mt", MyTransformation())
])

In [125]:
pipeline.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('poly', PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)), ('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('lr', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False))])

In [127]:
print("Train rmse:", rmse(y_train, pipeline.predict(X_train)))
print("Test rmse:", rmse(y_test, pipeline.predict(X_test)))

Train rmse: 4.24628389043
Test rmse: 4.27698829802


In [129]:
lr.coef_

array([ -1.10497225e+02,   1.09307670e+08,   1.90407910e+08,
         1.16278770e+08,   1.09030593e+08,   1.40155213e+07,
        -2.05643196e+07,  -4.23242446e+08,  -6.56987368e+06,
        -2.83197062e+07,  -7.29883639e+08,   7.74985143e+06,
        -4.32671326e+08,  -4.27465532e+08,  -1.05854836e+07,
         5.60179173e+05,  -3.69172061e+06,  -4.20785903e+07,
         1.27854611e+06,   5.31794539e+06,   6.28886792e+07,
        -3.76184994e+06,   6.14535901e+08,   1.85102181e+07,
         1.16861880e+06,  -8.80466908e+04,   7.96290777e+07,
         2.16715956e+06,   1.04960543e+09,  -2.13663889e+07,
        -1.69068574e+06,   6.01740807e+08,   6.28707551e+08,
         3.12135878e+07,   5.60720935e+05,  -3.49134896e+04,
         1.81236666e+05,  -1.08728443e+06,  -6.07614724e+04,
        -2.84265010e+05,   7.19355487e+06,   2.12247344e+05,
         4.21062721e+07,  -2.48459100e+06,  -5.12233991e+04,
         1.15216514e+05,  -1.02792945e+07,  -1.92408555e+05,
        -6.41016351e+07,

In [135]:
from sklearn.linear_model import Lasso, Ridge

In [133]:
lasso = Lasso()
lasso.fit(X_train_poly_std, y_train)
rmse(y_train, lasso.predict(X_train_poly_std))
rmse(y_test, lasso.predict(X_test_poly_std))

4.5962362395855223

In [134]:
lasso.coef_

array([  0.        , -10.45490559,  -2.45314101,   0.        ,
         0.        ,  -0.        ,  -0.        ,  -0.        ,
        -3.33700969,  -0.        ,  -0.        ,  -0.        ,
         0.        ,   0.        ,   0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.  

In [136]:
ridge = Ridge()
ridge.fit(X_train_poly_std, y_train)
rmse(y_train, ridge.predict(X_train_poly_std))
rmse(y_test, ridge.predict(X_test_poly_std))

4.1809287834472304

In [137]:
ridge.coef_

array([  0.        , -11.71173579,  -4.99762623,  15.27720726,
         5.56818926,  -3.75301039,  -2.72985364,  -6.96090318,
        -8.05803973,  -0.84127501,  -1.19137248,  -4.92386922,
         7.8289526 ,   2.14960717,  14.27943303,   1.11953494,
         2.55048676,  -0.66225073,  -3.78850943,   2.09893045,
        -2.474463  ,   0.5794708 ,  -2.35229616,  -2.70334555,
        -4.18860229,   3.07780944,  -1.62465551,  -0.56615695,
         2.40653428,  -0.98368579,  -4.52404291,   0.24156983,
        -1.66130129,   8.14090586,  11.6327457 ,  -6.3838145 ,
         7.48657611,   0.68023561,   6.54457884,   0.32056523,
        -0.66764291,   1.44135   ,   2.38559155,   1.65763387,
        -9.81163988,   1.50791668,  -2.76325494,   4.81069997,
        -2.27761937,   3.21716043,  -1.10462353,   2.10234609,
         2.48904637,  -2.42569295,   0.25322356,   5.54615411,
        -2.15575944,   2.21342262,  -2.47969567,   1.11569694,
        -5.09301096,   5.77364565,   2.74948931,  -4.25