In [16]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10, 20], [30, 40], [50, 60], [70, 80]])
scaler = StandardScaler()
scalerX = scaler.fit(data)

print(data)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [22]:
print(scalerX.mean_)
print(scalerX.var_)
scaled_data = scalerX.transform(data)
print(scaled_data)

[40. 50.]
[500. 500.]
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


In [18]:
scaled_data.mean(axis = 0)

array([0., 0.])

In [19]:
scaled_data.std(axis = 0)

array([1., 1.])